### ISSUE TITLE
Throws an error since few days ago, protocol changed?

### ISSUE THREAD

**Issue by neoromantic** [aloysius-pgast/bittrex-signalr-client#13]
```
/Users/sergey.petrov/dev//producer/node_modules/bittrex-signalr-client/lib/client.js:1424
            self._subscriptions.markets.pairs[pair].lastCseq = data.N;
                                                                    ^

TypeError: Cannot read property 'N' of null
    at SignalRClient.<anonymous> (/Users/sergey.petrov/dev/mosaic-dataplatform/producer/node_modules/bittrex-signalr-client/lib/client.js:1424:69)
    at InflateRaw.cb (/Users/sergey.petrov/dev/mosaic-dataplatform/producer/node_modules/bittrex-signalr-client/lib/client.js:2019:12)
    at InflateRaw.zlibBufferOnEnd (zlib.js:122:10)
    at InflateRaw.emit (events.js:187:15)
    at InflateRaw.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by neoromantic** [comment]
Seems like this error happen when subscribing to trades for non existing pair.

**Comment by aloysius-pgast** [comment]
Good catch, thanks ! Included in last version
